apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chuck-api
  namespace: chuck
spec:
  host: chuck-api.chuck.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chuck-api
  namespace: "chuck"
spec:
  hosts:
  - chuck-api.chuck.svc.cluster.local
  http:
  - route:
    - destination:
        host: chuck-api.chuck.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chuck-ui
  namespace: chuck
spec:
  host: chuck-ui.chuck.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chuck-ui
  namespace: "chuck"
spec:
  hosts:
  - chuck-ui.chuck.svc.cluster.local
  http:
  - route:
    - destination:
        host: chuck-ui.chuck.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chuck-db
  namespace: chuck
spec:
  host: chuck-db.chuck.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chuck-db
  namespace: "chuck"
spec:
  hosts:
  - chuck-db.chuck.svc.cluster.local
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: chuck-db.chuck.svc.cluster.local
        port:
          number: 3306
